### PR TITLE
Add auto player duck on mic live. Closes #70

### LINKED ISSUE #70: Have channel tickboxes for auto-duck on Mic
Essentially allows automatic dipping of beds/songs when the mic is live. Ease of use thing for those getting started.

### PR DESCRIPTION
**Pull request by mstratford**
Some people may not want to keep fading their bed/music down to talk. This adds a Pro-Mode :tm: toggle button to enable WebStudio to work the faders for you.

This does show a tad of performance issue drawing to the screen though, those tweens are drawing too often.

### CODE REVIEW

**Comment by markspolakovs** [comment]
@mstratford could you rebase this?

**Comment by mstratford** [comment]
> @mstratford could you rebase this?

Done :)

**Comment by markspolakovs** [comment]
Thanks, will test and merge in tonight.

**Comment by markspolakovs** [comment]
So, it works, but I have noticed quite a few perf problems when using it (which I oddly don't notice when fading using the usual shortcuts).

I dug into the React profiler and this is what I saw:

image

Couple things stand out to me:
* I faded down and up once, and it triggered 245 renders
* This bit here takes 2.2ms to render, and seems to render unnecessarily
image
* In general, items seem to render unnecessarily
image

**Comment by mstratford** [comment]
I know there's certainly something inefficient, I can sometimes get WebStudio to make my laptop to become a blow drier (sustained like 50% cpu while seemingly doing nothing).

**Comment by mstratford** [comment]
I think the major problem here is that between.js has no step limiting, it just goes as often and as quickly as it can. Same with the VU meters. This just means the CPU is as busy as it can be, which i'm not too much of a fan of.

**Comment by markspolakovs** [comment]
@mstratford... ugh, that's annoying. Am I going to have to write my own between clone that uses requestAnimationFrame?

**Comment by markspolakovs** [comment]
Okay, no, it does use rAF under the hood. Am I going to write my own clone that limits it to, say, an update every 50 or 100ms

**Comment by markspolakovs** [comment]
The VU meters I could probably refactor to not re-render the element each frame, which would save a few CPU cycles, although since it doesn't rerender anything above it I'm not sure how much it'd save.

Either way, I'll probably do those in separate PRs, so this and they can go in for 1.4.1 / 1.5.0.

**Comment by mstratford** [comment]
So i've updated the VUmetering stuff a bit in #186 to fix some rendering bugs. In #191 i've also rejigged the UI to not re-render the entire page on a show plan update, as well as limiting the VU meters to 30FPS to hopefully reduce stuttering on low end devices. Also looks a bit less frantic too.

**Comment by mstratford** [comment]
Current known bugs:
- PFL and Auto Duck interfere with fading eachother.
- Stil the update rate of the whole UI plummets when fading.

**Comment by mstratford** [comment]
Kinda want to merge this now, get people to test it. Leave the optimisation to what will be left of #191

**Comment by mstratford** [comment]
Taking some liberties and merging this to dev now. :)

**Pull request merged**
